/*
 * This file is generated by jOOQ.
 */
package pl.kuba565.resttask.jooq;


import javax.annotation.Generated;

import pl.kuba565.resttask.jooq.tables.Car;
import pl.kuba565.resttask.jooq.tables.Databasechangelog;
import pl.kuba565.resttask.jooq.tables.Databasechangeloglock;
import pl.kuba565.resttask.jooq.tables.Log;
import pl.kuba565.resttask.jooq.tables.Worker;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CAR</code>.
     */
    public static final Car CAR = Car.CAR;

    /**
     * The table <code>PUBLIC.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>PUBLIC.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>PUBLIC.LOG</code>.
     */
    public static final Log LOG = Log.LOG;

    /**
     * The table <code>PUBLIC.WORKER</code>.
     */
    public static final Worker WORKER = Worker.WORKER;
}
