/*
 * This file is generated by jOOQ.
 */
package pl.kuba565.resttask.jooq.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import pl.kuba565.resttask.jooq.tables.Car;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarRecord extends UpdatableRecordImpl<CarRecord> implements Record5<Integer, Long, BigDecimal, Short, String> {

    private static final long serialVersionUID = 1543388536;

    /**
     * Setter for <code>PUBLIC.CAR.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CAR.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CAR.LOG_ID</code>.
     */
    public void setLogId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CAR.LOG_ID</code>.
     */
    public Long getLogId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CAR.WEIGHT</code>.
     */
    public void setWeight(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CAR.WEIGHT</code>.
     */
    public BigDecimal getWeight() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CAR.NUMBER_OF_SEATS</code>.
     */
    public void setNumberOfSeats(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CAR.NUMBER_OF_SEATS</code>.
     */
    public Short getNumberOfSeats() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CAR.REGISTRATION_NUMBER</code>.
     */
    public void setRegistrationNumber(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CAR.REGISTRATION_NUMBER</code>.
     */
    public String getRegistrationNumber() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Long, BigDecimal, Short, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Long, BigDecimal, Short, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Car.CAR.ID;
    }

    @Override
    public Field<Long> field2() {
        return Car.CAR.LOG_ID;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Car.CAR.WEIGHT;
    }

    @Override
    public Field<Short> field4() {
        return Car.CAR.NUMBER_OF_SEATS;
    }

    @Override
    public Field<String> field5() {
        return Car.CAR.REGISTRATION_NUMBER;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getLogId();
    }

    @Override
    public BigDecimal component3() {
        return getWeight();
    }

    @Override
    public Short component4() {
        return getNumberOfSeats();
    }

    @Override
    public String component5() {
        return getRegistrationNumber();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getLogId();
    }

    @Override
    public BigDecimal value3() {
        return getWeight();
    }

    @Override
    public Short value4() {
        return getNumberOfSeats();
    }

    @Override
    public String value5() {
        return getRegistrationNumber();
    }

    @Override
    public CarRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CarRecord value2(Long value) {
        setLogId(value);
        return this;
    }

    @Override
    public CarRecord value3(BigDecimal value) {
        setWeight(value);
        return this;
    }

    @Override
    public CarRecord value4(Short value) {
        setNumberOfSeats(value);
        return this;
    }

    @Override
    public CarRecord value5(String value) {
        setRegistrationNumber(value);
        return this;
    }

    @Override
    public CarRecord values(Integer value1, Long value2, BigDecimal value3, Short value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CarRecord
     */
    public CarRecord() {
        super(Car.CAR);
    }

    /**
     * Create a detached, initialised CarRecord
     */
    public CarRecord(Integer id, Long logId, BigDecimal weight, Short numberOfSeats, String registrationNumber) {
        super(Car.CAR);

        set(0, id);
        set(1, logId);
        set(2, weight);
        set(3, numberOfSeats);
        set(4, registrationNumber);
    }
}
