/*
 * This file is generated by jOOQ.
 */
package pl.kuba565.resttask.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import pl.kuba565.resttask.jooq.tables.Log;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogRecord extends UpdatableRecordImpl<LogRecord> implements Record2<Integer, byte[]> {

    private static final long serialVersionUID = 571136066;

    /**
     * Setter for <code>PUBLIC.LOG.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.LOG.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.LOG.VALUE</code>.
     */
    public void setValue(byte... value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.LOG.VALUE</code>.
     */
    public byte[] getValue() {
        return (byte[]) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, byte[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, byte[]> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Log.LOG.ID;
    }

    @Override
    public Field<byte[]> field2() {
        return Log.LOG.VALUE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public byte[] component2() {
        return getValue();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public byte[] value2() {
        return getValue();
    }

    @Override
    public LogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LogRecord value2(byte... value) {
        setValue(value);
        return this;
    }

    @Override
    public LogRecord values(Integer value1, byte[] value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LogRecord
     */
    public LogRecord() {
        super(Log.LOG);
    }

    /**
     * Create a detached, initialised LogRecord
     */
    public LogRecord(Integer id, byte[] value) {
        super(Log.LOG);

        set(0, id);
        set(1, value);
    }
}
