/*
 * This file is generated by jOOQ.
 */
package pl.kuba565.resttask.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import pl.kuba565.resttask.jooq.tables.Worker;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkerRecord extends UpdatableRecordImpl<WorkerRecord> implements Record5<Integer, Long, String, String, String> {

    private static final long serialVersionUID = 1927874962;

    /**
     * Setter for <code>PUBLIC.WORKER.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.WORKER.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.WORKER.CAR_ID</code>.
     */
    public void setCarId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.WORKER.CAR_ID</code>.
     */
    public Long getCarId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.WORKER.PESEL</code>.
     */
    public void setPesel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.WORKER.PESEL</code>.
     */
    public String getPesel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.WORKER.NAME</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.WORKER.NAME</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.WORKER.SURNAME</code>.
     */
    public void setSurname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.WORKER.SURNAME</code>.
     */
    public String getSurname() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Long, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Long, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Worker.WORKER.ID;
    }

    @Override
    public Field<Long> field2() {
        return Worker.WORKER.CAR_ID;
    }

    @Override
    public Field<String> field3() {
        return Worker.WORKER.PESEL;
    }

    @Override
    public Field<String> field4() {
        return Worker.WORKER.NAME;
    }

    @Override
    public Field<String> field5() {
        return Worker.WORKER.SURNAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCarId();
    }

    @Override
    public String component3() {
        return getPesel();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getSurname();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCarId();
    }

    @Override
    public String value3() {
        return getPesel();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getSurname();
    }

    @Override
    public WorkerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public WorkerRecord value2(Long value) {
        setCarId(value);
        return this;
    }

    @Override
    public WorkerRecord value3(String value) {
        setPesel(value);
        return this;
    }

    @Override
    public WorkerRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public WorkerRecord value5(String value) {
        setSurname(value);
        return this;
    }

    @Override
    public WorkerRecord values(Integer value1, Long value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkerRecord
     */
    public WorkerRecord() {
        super(Worker.WORKER);
    }

    /**
     * Create a detached, initialised WorkerRecord
     */
    public WorkerRecord(Integer id, Long carId, String pesel, String name, String surname) {
        super(Worker.WORKER);

        set(0, id);
        set(1, carId);
        set(2, pesel);
        set(3, name);
        set(4, surname);
    }
}
