package pl.kuba565.resttask.model;

public abstract class BaseModel {
// I did not declare abstract Id getter and setter - because these are auto-generated by Lombok, and in such case I would have to double them in extending classes
}
